# Generated by Django 5.2.5 on 2026-02-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_biography_alter_author_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='authors', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(null=True, upload_to='books', verbose_name='Обложка'),
        ),
    ]
