# Generated by Django 5.2.5 on 2026-02-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_picture_book_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
